// Storage utilities for saving/loading material lists
import jsPDF from 'jspdf';

const STORAGE_KEY = 'pool_material_lists';
const MAX_LISTS = 20;

// Get all saved lists
export const getSavedLists = () => {
  try {
    const data = localStorage.getItem(STORAGE_KEY);
    return data ? JSON.parse(data) : [];
  } catch (e) {
    console.error('Error loading lists:', e);
    return [];
  }
};

// Save a new list
export const saveList = (list) => {
  try {
    const lists = getSavedLists();
    const newList = {
      ...list,
      id: Date.now().toString(),
      createdAt: new Date().toISOString(),
    };
    
    // Add to beginning, keep only last MAX_LISTS
    const updatedLists = [newList, ...lists].slice(0, MAX_LISTS);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedLists));
    return newList;
  } catch (e) {
    console.error('Error saving list:', e);
    return null;
  }
};

// Delete a list by ID
export const deleteList = (listId) => {
  try {
    const lists = getSavedLists();
    const updatedLists = lists.filter(l => l.id !== listId);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedLists));
    return true;
  } catch (e) {
    console.error('Error deleting list:', e);
    return false;
  }
};

// Get a single list by ID
export const getListById = (listId) => {
  const lists = getSavedLists();
  return lists.find(l => l.id === listId);
};

// Get unique site names from saved list history
export const getUsedSiteNames = () => {
  const lists = getSavedLists();
  const names = lists
    .map(l => l.siteName)
    .filter(name => name && name !== 'Untitled Site');
  return [...new Set(names)];
};

// Format list items for sharing
export const formatListForSharing = (items, siteName = '', date = '') => {
  let header = '';
  if (siteName) {
    header += `Site: ${siteName}\n`;
  }
  if (date) {
    header += `Date: ${date}\n`;
  }
  if (header) {
    header += '\n';
  }
  
  const itemsList = items
    .filter(item => item.quantity > 0)
    .map(item => `${item.name} – ${item.quantity} ${item.unit}`)
    .join('\n');
    
  return header + itemsList;
};

// Share via WhatsApp
export const shareViaWhatsApp = (text) => {
  const message = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${message}`, '_blank');
};

// Copy to clipboard
export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (e) {
    console.error('Failed to copy:', e);
    return false;
  }
};

// Generate PDF
export const generatePDF = (items, siteName = '', date = '') => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 25;
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Material List', pageWidth / 2, y, { align: 'center' });
  y += 15;
  
  // Site info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  if (siteName) {
    doc.setFont('helvetica', 'bold');
    doc.text('Site:', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(siteName, margin + 15, y);
    y += 8;
  }
  
  if (date) {
    doc.setFont('helvetica', 'bold');
    doc.text('Date:', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(date, margin + 15, y);
    y += 8;
  }
  
  // Separator line
  y += 5;
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  // Items
  doc.setFontSize(11);
  const filteredItems = items.filter(item => item.quantity > 0);
  
  filteredItems.forEach((item, index) => {
    // Check if we need a new page
    if (y > 270) {
      doc.addPage();
      y = 25;
    }
    
    const text = `${item.name} – ${item.quantity} ${item.unit}`;
    doc.text(text, margin, y);
    y += 7;
  });
  
  // Footer
  y = 280;
  doc.setFontSize(9);
  doc.setTextColor(128);
  doc.text('Generated by Pool Material List App', pageWidth / 2, y, { align: 'center' });
  
  // Generate filename
  const filename = siteName 
    ? `Material_List_${siteName.replace(/\s+/g, '_')}_${date.replace(/\//g, '-')}.pdf`
    : `Material_List_${date.replace(/\//g, '-')}.pdf`;
  
  doc.save(filename);
};

// Format date for display (DD-MM-YYYY)
export const formatDate = (date) => {
  const d = new Date(date);
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}-${month}-${year}`;
};

// Get today's date formatted
export const getTodayFormatted = () => {
  return formatDate(new Date());
};

// ===== USER MANAGEMENT =====
const USERS_KEY = 'bms_users';

export const getUsers = () => {
  try {
    const data = localStorage.getItem(USERS_KEY);
    return data ? JSON.parse(data) : [];
  } catch (e) {
    console.error('Error loading users:', e);
    return [];
  }
};

export const saveUser = (user) => {
  try {
    const users = getUsers();
    const newUser = {
      ...user,
      id: user.id || Date.now(),
      createdAt: user.createdAt || new Date().toISOString(),
    };
    
    const updatedUsers = [...users, newUser];
    localStorage.setItem(USERS_KEY, JSON.stringify(updatedUsers));
    return newUser;
  } catch (e) {
    console.error('Error saving user:', e);
    return null;
  }
};

// ===== TRANSACTION MANAGEMENT =====
const TRANSACTIONS_KEY = 'bms_transactions';

export const getTransactions = () => {
  try {
    const data = localStorage.getItem(TRANSACTIONS_KEY);
    return data ? JSON.parse(data) : [];
  } catch (e) {
    console.error('Error loading transactions:', e);
    return [];
  }
};

export const saveTransaction = (transaction) => {
  try {
    const transactions = getTransactions();
    const newTransaction = {
      ...transaction,
      id: transaction.id || Date.now(),
      createdAt: transaction.createdAt || new Date().toISOString(),
    };
    
    const updatedTransactions = [...transactions, newTransaction];
    localStorage.setItem(TRANSACTIONS_KEY, JSON.stringify(updatedTransactions));
    return newTransaction;
  } catch (e) {
    console.error('Error saving transaction:', e);
    return null;
  }
};

export const getUserTransactions = (userId) => {
  const transactions = getTransactions();
  return transactions.filter(t => t.userId === userId);
};

// ===== TRANSACTION PDF & SHARING =====

// Helper function to format currency for PDF (using Rs. instead of ₹)
const formatCurrencyForPDF = (amount) => {
  if (!amount && amount !== 0) return 'Rs. 0';
  
  const num = parseFloat(amount);
  if (isNaN(num)) return 'Rs. 0';
  
  // Convert to string and split into integer and decimal parts
  const [integerPart, decimalPart] = num.toFixed(2).split('.');
  
  // Indian numbering system: last 3 digits, then groups of 2
  let lastThree = integerPart.substring(integerPart.length - 3);
  const otherNumbers = integerPart.substring(0, integerPart.length - 3);
  
  if (otherNumbers !== '') {
    lastThree = ',' + lastThree;
  }
  
  const formatted = otherNumbers.replace(/\B(?=(\d{2})+(?!\d))/g, ',') + lastThree;
  
  // Return with decimal if not .00
  if (decimalPart && decimalPart !== '00') {
    return `Rs. ${formatted}.${decimalPart}`;
  }
  
  return `Rs. ${formatted}`;
};

// Generate PDF for user transactions
export const generateUserTransactionsPDF = (user, transactions, monthlyTotal, formatCurrency) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 25;
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('User Transaction History', pageWidth / 2, y, { align: 'center' });
  y += 15;
  
  // User info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('User:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(user.name, margin + 15, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Phone:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(user.phone, margin + 18, y);
  y += 8;
  
  const now = new Date();
  const monthName = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
  doc.setFont('helvetica', 'bold');
  doc.text('Period:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(monthName, margin + 18, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(formatCurrencyForPDF(monthlyTotal), margin + 15, y);
  y += 10;
  
  // Separator line
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  // Transactions
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Transactions:', margin, y);
  y += 8;
  
  doc.setFont('helvetica', 'normal');
  
  if (transactions.length === 0) {
    doc.text('No transactions found', margin, y);
  } else {
    transactions.forEach((transaction, index) => {
      // Check if we need a new page
      if (y > 260) {
        doc.addPage();
        y = 25;
      }
      
      const date = new Date(transaction.createdAt).toLocaleDateString('en-IN', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
      
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}.`, margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(date, margin + 8, y);
      y += 6;
      
      doc.text(`   Purpose: ${transaction.purpose}`, margin, y);
      y += 6;
      
      doc.setFont('helvetica', 'bold');
      doc.text(`   Amount: ${formatCurrencyForPDF(transaction.amount)}`, margin, y);
      doc.setFont('helvetica', 'normal');
      y += 8;
    });
  }
  
  // Footer
  const footerY = 280;
  doc.setFontSize(9);
  doc.setTextColor(128);
  doc.text('Generated by BMS Cash Entry', pageWidth / 2, footerY, { align: 'center' });
  
  // Generate filename
  const filename = `${user.name.replace(/\s+/g, '_')}_Transactions_${monthName.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
};

// Generate PDF for daily transactions
export const generateDailyTransactionsPDF = (date, transactions, dailyTotal, formatCurrency) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 25;
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Daily Transaction Report', pageWidth / 2, y, { align: 'center' });
  y += 15;
  
  // Date info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(date, margin + 15, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(formatCurrencyForPDF(dailyTotal), margin + 15, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Count:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`${transactions.length} transactions`, margin + 17, y);
  y += 10;
  
  // Separator line
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  // Transactions
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Transactions:', margin, y);
  y += 8;
  
  doc.setFont('helvetica', 'normal');
  
  transactions.forEach((transaction, index) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 25;
    }
    
    const time = new Date(transaction.createdAt).toLocaleTimeString('en-IN', {
      hour: '2-digit',
      minute: '2-digit'
    });
    
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}.`, margin, y);
    doc.text(time, margin + 8, y);
    doc.setFont('helvetica', 'normal');
    y += 6;
    
    doc.text(`   User: ${transaction.userName}`, margin, y);
    y += 6;
    
    doc.text(`   Phone: ${transaction.userPhone}`, margin, y);
    y += 6;
    
    doc.text(`   Purpose: ${transaction.purpose}`, margin, y);
    y += 6;
    
    doc.setFont('helvetica', 'bold');
    doc.text(`   Amount: ${formatCurrencyForPDF(transaction.amount)}`, margin, y);
    doc.setFont('helvetica', 'normal');
    y += 8;
  });
  
  // Footer
  const footerY = 280;
  doc.setFontSize(9);
  doc.setTextColor(128);
  doc.text('Generated by BMS Cash Entry', pageWidth / 2, footerY, { align: 'center' });
  
  // Generate filename
  const filename = `Daily_Transactions_${date.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
};

// Format user transactions for WhatsApp
export const formatUserTransactionsForWhatsApp = (user, transactions, monthlyTotal, formatCurrency) => {
  const now = new Date();
  const monthName = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
  
  let message = `*User Transaction History*\n\n`;
  message += `👤 *User:* ${user.name}\n`;
  message += `📱 *Phone:* ${user.phone}\n`;
  message += `📅 *Period:* ${monthName}\n`;
  message += `💰 *Total:* ${formatCurrency(monthlyTotal)}\n`;
  message += `\n━━━━━━━━━━━━━━━━━━\n\n`;
  
  if (transactions.length === 0) {
    message += `No transactions found`;
  } else {
    message += `*Transactions (${transactions.length}):*\n\n`;
    
    transactions.forEach((transaction, index) => {
      const date = new Date(transaction.createdAt).toLocaleDateString('en-IN', {
        day: 'numeric',
        month: 'short',
        hour: '2-digit',
        minute: '2-digit'
      });
      
      message += `${index + 1}. ${date}\n`;
      message += `   Purpose: ${transaction.purpose}\n`;
      message += `   Amount: ${formatCurrency(transaction.amount)}\n\n`;
    });
  }
  
  message += `\n_Generated by BMS Cash Entry_`;
  return message;
};

// Format daily transactions for WhatsApp
export const formatDailyTransactionsForWhatsApp = (date, transactions, dailyTotal, formatCurrency) => {
  let message = `*Daily Transaction Report*\n\n`;
  message += `📅 *Date:* ${date}\n`;
  message += `💰 *Total:* ${formatCurrency(dailyTotal)}\n`;
  message += `📊 *Count:* ${transactions.length} transactions\n`;
  message += `\n━━━━━━━━━━━━━━━━━━\n\n`;
  
  message += `*Transactions:*\n\n`;
  
  transactions.forEach((transaction, index) => {
    const time = new Date(transaction.createdAt).toLocaleTimeString('en-IN', {
      hour: '2-digit',
      minute: '2-digit'
    });
    
    message += `${index + 1}. ${time}\n`;
    message += `   👤 ${transaction.userName} (${transaction.userPhone})\n`;
    message += `   Purpose: ${transaction.purpose}\n`;
    message += `   Amount: ${formatCurrency(transaction.amount)}\n\n`;
  });
  
  message += `\n_Generated by BMS Cash Entry_`;
  return message;
};

// Generate Monthly Summary PDF (only daily totals)
export const generateMonthlySummaryPDF = (monthYear, dailySummaries, monthlyTotal, formatCurrency) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 25;
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Monthly Transaction Summary', pageWidth / 2, y, { align: 'center' });
  y += 15;
  
  // Month info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Period:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(monthYear, margin + 20, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Monthly Total:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(formatCurrencyForPDF(monthlyTotal), margin + 35, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Days:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`${dailySummaries.length} days`, margin + 15, y);
  y += 10;
  
  // Separator line
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  // Daily Summaries
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Daily Totals:', margin, y);
  y += 8;
  
  doc.setFont('helvetica', 'normal');
  
  dailySummaries.forEach((day, index) => {
    // Check if we need a new page
    if (y > 260) {
      doc.addPage();
      y = 25;
    }
    
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}.`, margin, y);
    doc.text(day.date, margin + 8, y);
    doc.setFont('helvetica', 'normal');
    doc.text(`(${day.count} transactions)`, margin + 50, y);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrencyForPDF(day.total), pageWidth - margin - 30, y);
    doc.setFont('helvetica', 'normal');
    y += 7;
  });
  
  // Footer
  const footerY = 280;
  doc.setFontSize(9);
  doc.setTextColor(128);
  doc.text('Generated by BMS Cash Others', pageWidth / 2, footerY, { align: 'center' });
  
  // Generate filename
  const filename = `Monthly_Summary_${monthYear.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
};

// Format monthly summary for WhatsApp (only daily totals)
export const formatMonthlySummaryForWhatsApp = (monthYear, dailySummaries, monthlyTotal, formatCurrency) => {
  let message = `*Monthly Transaction Summary*\n\n`;
  message += `📅 *Period:* ${monthYear}\n`;
  message += `💰 *Monthly Total:* ${formatCurrency(monthlyTotal)}\n`;
  message += `📊 *Days:* ${dailySummaries.length} days\n`;
  message += `\n━━━━━━━━━━━━━━━━━━\n\n`;
  
  message += `*Daily Totals:*\n\n`;
  
  dailySummaries.forEach((day, index) => {
    message += `${index + 1}. ${day.date}\n`;
    message += `   ${formatCurrency(day.total)} (${day.count} transactions)\n\n`;
  });
  
  message += `\n_Generated by BMS Cash Others_`;
  return message;
};
