// Storage utilities for saving/loading material lists
import jsPDF from 'jspdf';

const STORAGE_KEY = 'pool_material_lists';
const MAX_LISTS = 5;

// Get all saved lists
export const getSavedLists = () => {
  try {
    const data = localStorage.getItem(STORAGE_KEY);
    return data ? JSON.parse(data) : [];
  } catch (e) {
    console.error('Error loading lists:', e);
    return [];
  }
};

// Save a new list
export const saveList = (list) => {
  try {
    const lists = getSavedLists();
    const newList = {
      ...list,
      id: Date.now().toString(),
      createdAt: new Date().toISOString(),
    };
    
    // Add to beginning, keep only last MAX_LISTS
    const updatedLists = [newList, ...lists].slice(0, MAX_LISTS);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedLists));
    return newList;
  } catch (e) {
    console.error('Error saving list:', e);
    return null;
  }
};

// Delete a list by ID
export const deleteList = (listId) => {
  try {
    const lists = getSavedLists();
    const updatedLists = lists.filter(l => l.id !== listId);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updatedLists));
    return true;
  } catch (e) {
    console.error('Error deleting list:', e);
    return false;
  }
};

// Get a single list by ID
export const getListById = (listId) => {
  const lists = getSavedLists();
  return lists.find(l => l.id === listId);
};

// Format list items for sharing
export const formatListForSharing = (items, siteName = '', date = '') => {
  let header = '';
  if (siteName) {
    header += `Site: ${siteName}\n`;
  }
  if (date) {
    header += `Date: ${date}\n`;
  }
  if (header) {
    header += '\n';
  }
  
  const itemsList = items
    .filter(item => item.quantity > 0)
    .map(item => `${item.name} – ${item.quantity} ${item.unit}`)
    .join('\n');
    
  return header + itemsList;
};

// Share via WhatsApp
export const shareViaWhatsApp = (text) => {
  const message = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${message}`, '_blank');
};

// Copy to clipboard
export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (e) {
    console.error('Failed to copy:', e);
    return false;
  }
};

// Generate PDF
export const generatePDF = (items, siteName = '', date = '') => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 25;
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Material List', pageWidth / 2, y, { align: 'center' });
  y += 15;
  
  // Site info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  if (siteName) {
    doc.setFont('helvetica', 'bold');
    doc.text('Site:', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(siteName, margin + 15, y);
    y += 8;
  }
  
  if (date) {
    doc.setFont('helvetica', 'bold');
    doc.text('Date:', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(date, margin + 15, y);
    y += 8;
  }
  
  // Separator line
  y += 5;
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  // Items
  doc.setFontSize(11);
  const filteredItems = items.filter(item => item.quantity > 0);
  
  filteredItems.forEach((item, index) => {
    // Check if we need a new page
    if (y > 270) {
      doc.addPage();
      y = 25;
    }
    
    const text = `${item.name} – ${item.quantity} ${item.unit}`;
    doc.text(text, margin, y);
    y += 7;
  });
  
  // Footer
  y = 280;
  doc.setFontSize(9);
  doc.setTextColor(128);
  doc.text('Generated by Pool Material List App', pageWidth / 2, y, { align: 'center' });
  
  // Generate filename
  const filename = siteName 
    ? `Material_List_${siteName.replace(/\s+/g, '_')}_${date.replace(/\//g, '-')}.pdf`
    : `Material_List_${date.replace(/\//g, '-')}.pdf`;
  
  doc.save(filename);
};

// Format date for display (DD-MM-YYYY)
export const formatDate = (date) => {
  const d = new Date(date);
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}-${month}-${year}`;
};

// Get today's date formatted
export const getTodayFormatted = () => {
  return formatDate(new Date());
};
